### PR TITLE
Html

### PR DESCRIPTION
**Pull request by natdjerf**
Initial bones for HTML & user actions. Updated the form fields from the standard ones to leverage built in materialize form highlighting features.

### CODE REVIEW

**Comment by cuprous** [comment]
I'm OK with merging this. @Benjamski @rdelvallej32 Are you two OK with this?

**Comment by BenGitsCode** [comment]
Looks good to me. @rdelvallej32 ?

**Comment by rdelvallej32** [comment]
Good to merge

**Comment by cuprous** [comment]
Resubmit with request to merge into development.

**Pull request closed without merging**
